/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import ckeditor from "@_sh/strapi-plugin-ckeditor/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import sentry from "@strapi/plugin-sentry/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import emailDesigner from "strapi-plugin-email-designer/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "color-picker": colorPicker,
    documentation: documentation,
    ckeditor: ckeditor,
    graphql: graphql,
    i18n: i18N,
    sentry: sentry,
    "users-permissions": usersPermissions,
    "email-designer": emailDesigner,
    "rest-cache": restCache,
  },
});
